# Compartments
BACTERIUM_EXTRACELLULAR_REPLICATING = 'B_er'
BACTERIUM_EXTRACELLULAR_DORMANT = 'B_ed'
EXTRACELLULAR_BACTERIA = [BACTERIUM_EXTRACELLULAR_REPLICATING, BACTERIUM_EXTRACELLULAR_DORMANT]
BACTERIUM_INTRACELLULAR_DENDRITIC = 'B_id'
BACTERIUM_INTRACELLULAR_MACROPHAGE = 'B_im'
INTRACELLULAR_BACTERIA = [BACTERIUM_INTRACELLULAR_DENDRITIC, BACTERIUM_INTRACELLULAR_MACROPHAGE]
BACTERIA = EXTRACELLULAR_BACTERIA + INTRACELLULAR_BACTERIA

MACROPHAGE_RESTING = 'M_r'
MACROPHAGE_INFECTED = 'M_i'
MACROPHAGE_ACTIVATED = 'M_a'
MACROPHAGES = [MACROPHAGE_RESTING, MACROPHAGE_INFECTED, MACROPHAGE_ACTIVATED]

DENDRITIC_CELL_IMMATURE = 'D_i'
DENDRITIC_CELL_MATURE = 'D_m'
DENDRITIC_CELLS = [DENDRITIC_CELL_IMMATURE, DENDRITIC_CELL_MATURE]

T_CELL_NAIVE = 'T_n'
T_CELL_ACTIVATED = 'T_a'
T_CELLS = [T_CELL_NAIVE, T_CELL_ACTIVATED]

TB_COMPARTMENTS = BACTERIA + MACROPHAGES + DENDRITIC_CELLS + T_CELLS

ACTIVATED_CELL = {MACROPHAGE_RESTING: MACROPHAGE_ACTIVATED, T_CELL_NAIVE: T_CELL_ACTIVATED}
INFECTED_CELL = {MACROPHAGE_RESTING: MACROPHAGE_INFECTED, DENDRITIC_CELL_IMMATURE: DENDRITIC_CELL_MATURE}
INTERNAL_BACTERIA_FOR_CELL = {MACROPHAGE_INFECTED: BACTERIUM_INTRACELLULAR_MACROPHAGE,
                              DENDRITIC_CELL_MATURE: BACTERIUM_INTRACELLULAR_DENDRITIC}
