from move import *
from change import *
from birth import *
from death import *
from mccormackbirth import *
from mccormackdeath import *
from mccormackinfection import *
from mccormackmove import *
from mccormackrecover import *